"""Publish a binary search index as bounded, automatically loadable local scripts.

Classic script elements work from file:// without granting a page arbitrary file
access. Each script contains only a callback and base64 data generated by OWL.
The logical OWLIDX2 index is unchanged; its temporary binary is not duplicated
in finished drives. A generation is immutable and its manifest is published last.
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
from pathlib import Path
import re

from .safety import SafetyError, atomic_write, guard_directory, safe_path


CHUNK_BYTES = 1024 * 1024
TRANSPORT_VERSION = 1
MANIFEST_PATH = "SEARCH/manifest.js"


def _json(value) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("ascii")


def _validate(manifest: dict) -> None:
    if (not isinstance(manifest, dict) or manifest.get("version") != TRANSPORT_VERSION
            or not isinstance(manifest.get("index_sha256"), str)
            or not re.fullmatch(r"[0-9a-f]{64}", manifest["index_sha256"])
            or type(manifest.get("size")) is not int or manifest["size"] < 4096
            or manifest.get("chunk_bytes") != CHUNK_BYTES
            or type(manifest.get("chunk_count")) is not int
            or not 1 <= manifest["chunk_count"] <= 100_000_000
            or manifest["chunk_count"] != (manifest["size"] + CHUNK_BYTES - 1) // CHUNK_BYTES):
        raise ValueError("Invalid automatic search manifest")


def chunk_path(manifest: dict, number: int) -> str:
    _validate(manifest)
    if type(number) is not int or not 0 <= number < manifest["chunk_count"]:
        raise ValueError("Invalid search chunk number")
    return f"SEARCH/chunks/{manifest['index_sha256']}/{number:08d}.js"


def _owner(manifest: dict) -> tuple[str, bytes]:
    return (f"SEARCH/chunks/{manifest['index_sha256']}/owner.json",
            _json({"owner": "offline-wandering-library-search-chunks",
                   "schema_version": 1, "index_sha256": manifest["index_sha256"]}) + b"\n")


def _manifest_script(manifest: dict) -> bytes:
    return b"globalThis.OWLSearchManifest(" + _json(manifest) + b");\n"


def _chunk_prefix(manifest: dict, number: int) -> bytes:
    return f'globalThis.OWLSearchChunk("{manifest["index_sha256"]}",{number},"'.encode("ascii")


def _chunk_script(manifest: dict, number: int, data: bytes) -> bytes:
    return _chunk_prefix(manifest, number) + base64.b64encode(data) + b'");\n'


def _integrity(data: bytes) -> dict:
    return {"sha256": hashlib.sha256(data).hexdigest(), "size_bytes": len(data)}


def _read_bounded(path: Path, maximum: int) -> bytes:
    if not path.is_file():
        raise ValueError("Search data must be a regular file")
    if path.stat().st_size > maximum:
        raise ValueError("Oversized search chunk or manifest")
    with path.open("rb") as handle:
        data = handle.read(maximum + 1)
    if len(data) > maximum:
        raise ValueError("Search file changed while reading")
    return data


def read_chunk(target: Path, manifest: dict, number: int) -> tuple[bytes, dict]:
    """Decode one generated data script without executing it, using bounded RAM."""
    path = safe_path(target, chunk_path(manifest, number))
    script = _read_bounded(path, 4 * ((CHUNK_BYTES + 2) // 3) + 256)
    prefix = _chunk_prefix(manifest, number)
    if not script.startswith(prefix) or not script.endswith(b'");\n'):
        raise ValueError("Invalid search chunk wrapper")
    data = base64.b64decode(script[len(prefix):-4], validate=True)
    expected = min(CHUNK_BYTES, manifest["size"] - number * CHUNK_BYTES)
    if len(data) != expected:
        raise ValueError("Truncated search chunk")
    return data, _integrity(script)


def packed_size(size: int, digest: str) -> int:
    """Exact generated chunk/manifest/owner bytes, without reading the corpus."""
    count = (size + CHUNK_BYTES - 1) // CHUNK_BYTES
    manifest = {"version": TRANSPORT_VERSION, "index_sha256": digest, "size": size,
                "chunk_bytes": CHUNK_BYTES, "chunk_count": count}
    _validate(manifest)
    total = len(_owner(manifest)[1]) + len(_manifest_script(manifest))
    # Each callback contains its decimal chunk number; no giant placeholder
    # strings or index-sized buffers are constructed for this calculation.
    total += sum(len(_chunk_prefix(manifest, number)) + 4 for number in range(count))
    total += (count - 1) * (4 * ((CHUNK_BYTES + 2) // 3))
    total += 4 * ((size - (count - 1) * CHUNK_BYTES + 2) // 3)
    return total


def publish_pack(target: Path, index: Path, digest: str, *, notify=lambda *_a, **_k: None,
                 max_bytes: int | None = None) -> dict:
    """Write/resume this owned generation, then atomically switch the manifest.

    No previous generation or unrelated file is removed. Existing chunk scripts
    are reused only when every byte equals the expected generated script.
    """
    size = index.stat().st_size
    manifest = {"version": TRANSPORT_VERSION, "index_sha256": digest, "size": size,
                "chunk_bytes": CHUNK_BYTES, "chunk_count": (size + CHUNK_BYTES - 1) // CHUNK_BYTES}
    _validate(manifest)
    if max_bytes is not None and packed_size(size, digest) > max_bytes:
        raise ValueError(f"Search script output exceeds search_budget_bytes ({max_bytes:,}); "
                         "increase the allowance or reduce selected content and rerun. The extraction checkpoint is retained.")
    owner_path, owner_data = _owner(manifest)
    marker = safe_path(target, owner_path)
    directory = marker.parent
    if directory.exists():
        if marker.exists():
            if _read_bounded(marker, 1024) != owner_data:
                raise SafetyError(f"Unrecognized search chunk directory: {directory}")
        elif any(directory.iterdir()):
            raise SafetyError(f"Refusing unowned search chunk directory: {directory}")
    directory.mkdir(parents=True, exist_ok=True)
    files = {}
    pending = []
    with guard_directory(directory):
        atomic_write(marker, owner_data)
        files[owner_path] = _integrity(owner_data)
        whole = hashlib.sha256()
        with index.open("rb") as source:
            for number in range(manifest["chunk_count"]):
                data = source.read(CHUNK_BYTES)
                whole.update(data)
                expected = min(CHUNK_BYTES, size - number * CHUNK_BYTES)
                if len(data) != expected:
                    raise ValueError("Search binary changed during packaging")
                relative = chunk_path(manifest, number)
                path = safe_path(target, relative)
                script = _chunk_script(manifest, number, data)
                if (not path.exists() or path.stat().st_size != len(script)
                        or _read_bounded(path, len(script)) != script):
                    staged = safe_path(target, relative + ".part")
                    if (not staged.exists() or staged.stat().st_size != len(script)
                            or _read_bounded(staged, len(script)) != script):
                        atomic_write(staged, script)
                    pending.append(relative)
                files[relative] = _integrity(script)
                notify(f"INDEX packaging local chunks: {number + 1:,}/{manifest['chunk_count']:,}")
            if source.read(1) or whole.hexdigest() != digest:
                raise ValueError("Search binary checksum changed during packaging")
        # Even an existing generation must remain intact if the raw staging
        # file changed after hashing. Promote repairs/new chunks only after
        # checking all input bytes. Identical chunks need no second copy.
        for relative in pending:
            staged = safe_path(target, relative + ".part")
            destination = safe_path(target, relative)
            os.replace(staged, destination)
        # Remove only our exact temporary chunk names after successful staging.
        # A failed prior attempt can leave a partial beside an unchanged final.
        for number in range(manifest["chunk_count"]):
            staged = safe_path(target, chunk_path(manifest, number) + ".part")
            if staged.exists():
                if not staged.is_file():
                    raise SafetyError(f"Unexpected search staging file: {staged}")
                staged.unlink()
        script = _manifest_script(manifest)
        atomic_write(safe_path(target, MANIFEST_PATH), script)
        files[MANIFEST_PATH] = _integrity(script)
    return {"transport": manifest, "file_integrity": files,
            "transport_bytes": sum(item["size_bytes"] for item in files.values())}


def verify_pack(target: Path, report: dict) -> bytes:
    """Check all current scripts and logical binary integrity; return its header."""
    manifest = report["transport"]
    _validate(manifest)
    if (not isinstance(report.get("file_integrity"), dict)
            or not isinstance(report.get("generated_files"), list)
            or len(report["file_integrity"]) != manifest["chunk_count"] + 4
            or len(report["generated_files"]) != manifest["chunk_count"] + 5):
        raise ValueError("Invalid search output integrity metadata")
    expected_paths = {_owner(manifest)[0], MANIFEST_PATH, "SEARCH.html", "SEARCH/search.js",
                      *(chunk_path(manifest, number) for number in range(manifest["chunk_count"]))}
    if (set(report["file_integrity"]) != expected_paths
            or set(report["generated_files"]) != expected_paths | {"SEARCH/coverage.json"}):
        raise ValueError("Unexpected search output paths")
    if (manifest["size"] != report["index_bytes"]
            or manifest["index_sha256"] != report["index_sha256"]):
        raise ValueError("Search report and manifest differ")
    owner_path, owner_data = _owner(manifest)
    checks = {owner_path: owner_data, MANIFEST_PATH: _manifest_script(manifest)}
    for relative, expected in checks.items():
        data = _read_bounded(safe_path(target, relative), 1024)
        if data != expected or report["file_integrity"].get(relative) != _integrity(data):
            raise ValueError("Search manifest or ownership changed")
    whole = hashlib.sha256()
    header = b""
    for number in range(manifest["chunk_count"]):
        data, integrity = read_chunk(target, manifest, number)
        if report["file_integrity"].get(chunk_path(manifest, number)) != integrity:
            raise ValueError("Search chunk checksum differs")
        if number == 0:
            header = data[:4096]
        whole.update(data)
    if whole.hexdigest() != manifest["index_sha256"]:
        raise ValueError("Logical search index checksum differs")
    return header
